### ISSUE TITLE
ProcessCollector support labels

### ISSUE THREAD

**Issue by QingsongYao** [prometheus/client_python#179]
When I have multiple instances runnings belong a LB, there is no way to know which instance the count value belong to.   I wonder if we can expose labels, just like Counter, etc so that I can assign labels to  ProcessCollector instead of using prefix.

**Comment by brian-brazil** [comment]
Your problem there is that you're accessing instances via a load balancer. Have Prometheus scrape each instance directly.

**Comment by danni-m** [comment]
@brian-brazil I came across the same issue, we are running multiple processes (that are written in C) and we want to monitor them for basic operational metrics.
Since we don't want to create multiple endpoints for prometheus and we don't write to code this directly into the C code, we prefer to label each one of the processes with a different label value (our logical identification).

Also since this is a list of PIDs we needed to accommodate both.

**Comment by brian-brazil** [comment]
The Prometheus approach is to run a exporter per process. Or you could get the processes to expose Prometheus metrics directly.

**Comment by danni-m** [comment]
@brian-brazil Yes, but if I have 40+ processes on a single box and every one of them will have a prometheus endpoint then I will need to create a service discovery just to find out their ports.
Also, in my case these are native processes that adding prometheus client is a big hassle.

Anyway, I understand you approach as the maintainer and leader of the project, and its important to set a standard. People will have different needs, they will write their own implementation for these needs which might create unwanted forks.

**Comment by brian-brazil** [comment]
> every one of them will have a prometheus endpoint then I will need to create a service discovery just to find out their ports.

Yes, this is the expected way that you run your system. You need service discovery one way or the other, what you're proposing requires the same.

**Comment by WoLpH** [comment]
I'm currently running into a similar issue, a Python process is starting/stopping multiple binary processes (I don't have the source) and fully manages them (including output capturing). These processes are fully linked so that if the Python process dies, so do all the subprocesses.

To get some extra metrics I would like to use the `ProcessCollector` but having something like this really clutters Prometheus:
```python
ProcessCollector('process_name_%s' % some_identifier, pid=...)
```

Ideally the `ProcessCollector` would support an optional `labels` argument so I could pass along identification about these processes. This seems like something that would be fairly trivial to implement but I'm not sure what your look on this option is @brian-brazil 

Running a process_exporter instead could work but I would lose valuable identification information about the process requiring me to cross-reference the pids for all lookups.

**Comment by brian-brazil** [comment]
That wouldn't quite work, as you'd still need to merge the resultant metric families together to produce valid output.

**Comment by WoLpH** [comment]
**DISCLAIMER: THIS CODE IS NOT RECOMMENDED IN PRODUCTION**

I've quickly hacked together this bit and to my untrained eye it appears to function correctly:
```python
class ProcessCollector(prometheus_client.ProcessCollector):

    def __init__(self, namespace='', pid=lambda: 'self', proc='/proc'
                 registry=prometheus_client.REGISTRY, labels=None):
        self.labels = labels
        prometheus_client.ProcessCollector.__init__(
            self, namespace, pid, proc, registry)

    def collect(self):
        results = prometheus_client.ProcessCollector.collect(self)
        for result in results:
            result._labelnames = tuple(self.labels)
            result.samples = [(name, self.labels, value)
                              for (name, _, value) in result.samples]

        return results

    def describe(self):
        return []
```

It's less than ideal though, especiallly having to overwrite the `describe` because the collector doesn't take labels into account.

**Comment by brian-brazil** [comment]
It'll appear to work, but that's not technically valid text format as you'll have duplicate metric families.

**Comment by WoLpH** [comment]
You are reight of course, I suppose this is a slightly better solution, still a hack though:

```python
lass MultiProcessCollector(prometheus_client.ProcessCollector):

   def __init__(self, namespace, labels, proc='/proc',
                registry=prometheus_client.REGISTRY):
       self.pids = dict()
       self.labels = labels
       prometheus_client.ProcessCollector.__init__(
           self, namespace, proc=proc, registry=registry)

   def add_pid(self, pid, labels):
       self.pids[pid] = labels

   def remove_pid(self, pid):
       del self.pids[pid]

   def collect(self):
       assert self.pids, 'No processes to collect'

       aggregated_results = dict()
       for pid, labels in self.pids.items():
           self._pid = lambda: pid

           for result in prometheus_client.ProcessCollector.collect(self):
               if result.name not in aggregated_results:
                   aggregated_results[result.name] = result
                   result._labelnames = tuple(self.labels)

               aggregated_result = aggregated_results[result.name]
               aggregated_result.samples += [
                   (name, labels, value)
                   for (name, _, value) in result.samples]

       return aggregated_results.values()

   def describe(self):
       # Using our own process for describing
       self._pid = lambda: 'self'
       return prometheus_client.ProcessCollector.collect(self)
```

**Comment by brian-brazil** [comment]
From a quick glance, that looks about right.
