### ISSUE TITLE
Collision in multi-process mode

### ISSUE THREAD

**Issue by vvkuznetsov** [prometheus/client_python#191]
Hello @brian-brazil.

In our project we use celery. And we experience a bug when all workers write to one file created by the master process. It's happening because metrics are initialized before fork and an open file is inherited by the child process. `_MmapedValue` in the child is created correctly, with new `pid`, so the child doesn't know that files belong to another process.

---
PR: https://github.com/prometheus/client_python/pull/192

**Comment by brian-brazil** [comment]
Are you sure you're using the latest release of the client? This should all work correctly already.

**Comment by vvkuznetsov** [comment]
yes, we noticed corrupted metric files before `0.0.20`, switch to the newest version and it didn't help.

**Comment by vvkuznetsov** [comment]
please inform me, if you have in mind other ways to fix this issue.

**Comment by brian-brazil** [comment]
Looking at the code I don't see how this is happening. If there's a fork then the pid will change, the files will be closed in the child and new files opened.

**Comment by megabuz** [comment]
@brian-brazil 
let's say we have two summary metrics
metric1 initialized in master and we have nonlocal `files = {'summary': ...}` initialized after that
metric2 initialized only in child. `__reset` called from `__init__` and set `self._pid` in instance as child pid
`__reset` function see `files = {'summary': ...}` from master and use master filepath
condition in `__check_for_pid_change` for metric2 will not pass because `self._pid` is already child pid there

**Comment by brian-brazil** [comment]
I see what you're saying now.
