### ISSUE TITLE
Script to export node exporter data to prometheus with timestamp

### ISSUE THREAD

**Issue by roshu10** [prometheus/client_python#195]
Hey guys,

I'm trying to push node exporter data to prometheus server.

used the following script:

from prometheus_client import CollectorRegistry, Gauge, push_to_gateway
registry = CollectorRegistry()
g = Gauge('job_last_success_unixtime', 'Last time a batch job successfully finished', registry=registry)
g.set_to_current_time()
status = push_to_gateway('52.x.x.x:9091', job='node', registry=registry)

This was successful, however, instance name was set to ""

How do we send instance name along with this.

Also, i want to send whole node exporter data at once.

How can we achieve this.

I'm not able to find much help on this in internet.

Thanks for any help !! :)

**Comment by brian-brazil** [comment]
This is not supported, and never will be. Don't use timestamps with the pushgateway.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by roshu10** [comment]
@brian-brazil  sure, but specifying label is also not possible ??
