### ISSUE TITLE
how to use Gauge append lables

### ISSUE THREAD

**Issue by WB-jastme** [prometheus/client_python#196]
hello, there is problem with me
i used Gauge to set value.
 get key value like this:
`gs_1001_cpu 0.0`

but now i want get key value like this:
`python_info{implementation="CPython",major="2",minor="6",patchlevel="6",version="2.6.6"} 1.0`

i do not know how to append labels in Gauge.please help me,thank you.

i am sorry my poor english.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
