### ISSUE TITLE
the value never changed request by http

### ISSUE THREAD

**Issue by WB-jastme** [prometheus/client_python#197]
`from prometheus_client import Gauge
from prometheus_client import start_http_server
import random

g = Gauge('gg', 'A gauge')
g.set(random.random())

start_http_server(8000)
import time
while True:
  time.sleep(1)`

when i request by http,the value never changed,how can i do?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
