### ISSUE TITLE
Change label value

### ISSUE THREAD

**Issue by azlador** [prometheus/client_python#213]
I try to add time Gauge metric to my tornado application
But I have not found examples how to set or change labels after initializing the time metric  
Code example below:

```
labels = ['method', 'endpoint', 'response_code', 'hostname']
time_metric = Gauge('api_request_miliseconds', 'request time', labels, registry=registry)

class Handler(tornado.web.RequestHandler):
    #....
    def get(self, *args, **kwargs):
        with time_metric.labels(**self.label_values).time() as tm:  # set default response_code=200 label value
            try:
                self.do_call()
            except Exception, e:
                self.error()
            finally:
                tm.set_label_value_magic(response_code=self.response_code) # need to change response_code which is already installed
```
Is it possible to change it?

**Comment by brian-brazil** [comment]
This is not possible, you need to know the label before calling observe.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
