### ISSUE TITLE
broken travis.yml: 2.6 does not support pytest  

### ISSUE THREAD

**Issue by ioggstream** [prometheus/client_python#216]
## I expect

travis gate to work with py26

## Instead

I get the following error when installing pytest

```
...
cmdargs: ['/home/travis/build/prometheus/client_python/.tox/py26/bin/pip', 'install', 'coverage', 'pytest', 'unittest2']
...

Collecting py>=1.5.0 (from pytest)
  Could not find a version that satisfies the requirement py>=1.5.0 (from pytest) (from versions: 0.9.1, 0.9.2, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7.dev3, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.4.23, 1.4.24, 1.4.25, 1.4.26, 1.4.27, 1.4.28, 1.4.29, 1.4.30, 1.4.31, 1.4.32, 1.4.33, 1.4.34)
No matching distribution found for py>=1.5.0 (from pytest)
```

**Comment by brian-brazil** [comment]
Looks like something broke on Travis's end in the past month.

**Comment by hugovk** [comment]
Pytest and its dependency py have dropped support for Python 2.6 because it's been EOL for four years meaning it hasn't received security updates, and it's also little used so it's about time to drop it. They also dropped support for Python 3.3 which is also EOL and little used.

Here's the pip installs for prometheus_client from PyPI for the last month (via `pypinfo --percent --pip prometheus_client pyversion`).

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   61.2% |         44,829 |
| 3.6            |   21.0% |         15,367 |
| 3.5            |   13.5% |          9,890 |
| 3.4            |    4.0% |          2,947 |
| 3.7            |    0.2% |            116 |
| 2.6            |    0.1% |             87 |
| 3.3            |    0.1% |             48 |
| 3.2            |    0.0% |              1 |

I suggest client_python also drops 2.6 and 3.3.

**Comment by brian-brazil** [comment]
Do we know if there are any popular OSes that still use 2.6, such as RHEL?

**Comment by hugovk** [comment]
RHEL 6 ships with 2.6 and RHEL 5 ships with 2.4.

![image](https://user-images.githubusercontent.com/1324225/33605927-5489b9b8-d9c4-11e7-8bb3-808f0daea01a.png)

https://en.wikipedia.org/wiki/CPython#Enterprise_Linux

But a secure Python can be installed using SCL:

https://developers.redhat.com/blog/2013/02/14/setting-up-django-and-python-2-7-on-red-hat-enterprise-6-the-easy-way/

**Comment by ioggstream** [comment]
iiuc this could work.

```
[testenv:py26]
deps= ... pytest==x.y.z

```

**Comment by ioggstream** [comment]
Another way to close this issue.

@hugovk: I still have to run prometheus_client on RHEL6 too

**Comment by hugovk** [comment]
Do you have a plan to upgrade RHEL/Python?

**Comment by ioggstream** [comment]
@hugovk I got a bunch of customers with various RHEL versions including 6, so no dropout for now :(

**Comment by ioggstream** [comment]
@brian-brazil closing for now
@hugovk you can create a new ticket for deprecating py26. It will surely be useful in the near future!

**Comment by hugovk** [comment]
Done! https://github.com/prometheus/client_python/issues/219
