### ISSUE TITLE
How set new value?

### ISSUE THREAD

**Issue by drno-reg** [prometheus/client_python#232]
Hello,

I used this code

from prometheus_client import Counter
c = Counter('my_requests_total', 'HTTP Failures', ['method', 'endpoint'])
c.labels('get', '/').inc()
c.labels('post', '/submit').inc()

after avery request c.labels('get', '/') add plus new value.

How every request set new value?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
