### ISSUE TITLE
"registry" argument doesn't work?

### ISSUE THREAD

**Issue by jeffwji** [prometheus/client_python#253]
The official example led me to a weird issue, not sure is my fault or the API has been changed?

Code:

    from prometheus_client import Counter, Gauge, Summary, Histogram
    from prometheus_client.core import  CollectorRegistry
    
    registry = CollectorRegistry(auto_describe=False)
    requests_total = Counter("requests_total", "Total count of requests", registry=registry)

Error message

    [pylint] E1123:Unexpected keyword argument 'registry' in constructor call
    [pylint] E1120:No value for argument 'labelvalues' in constructor call

**Comment by brian-brazil** [comment]
That works fine for me. Maybe you're using a very old version?

**Comment by jeffwji** [comment]
I'm using 0.1.1, is it the latest version? in this version, the construction function is:

    class Histogram(object):
        ....
        def __init__(self, name, labelnames, labelvalues, buckets=(.005, .01, .025, .05, .075, .1, .25, .5, .75, 1.0, 2.5, 5.0, 7.5, 10.0, _INF)):

**Comment by jeffwji** [comment]
I see though..., the decorator `_MetricWrapper` has `register` argument, maybe something else causes the error...

**Comment by moadqassem** [comment]
@jeffwji I am using the same version and it's working, I am not getting the error that you are getting. 
btw you can still import `CollectorRegistry` in the `from prometheus_client import Counter, Gauge, Summary, Histogram` because the `CollectorRegistry` is already imported in the `prometheus_client.py` `CollectorRegistry = core.CollectorRegistry`

**Comment by brian-brazil** [comment]
I don't see any bug here.
