### ISSUE TITLE
Histogram resets when client restarts

### ISSUE THREAD

**Issue by yanglu0106** [prometheus/client_python#259]
Please correct me if I'm wrong. `Counter` will be reset to 0 if the prometheus client restarts, while `Histogram` data would remain the same. Is there anyway to reset the histogram as well?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
