### ISSUE TITLE
Why gauges cant be like others in multiprocess mode?

### ISSUE THREAD

**Issue by macher91** [prometheus/client_python#267]
Hi, Like in title. I need for example number of registered users in django app. Number of users can be increment or reduced, so I cant use counter. Also gauges are not fitting for my problems when is used multiprocess mode.
But why there is no option to take last value from multi threads?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
