### ISSUE TITLE
Labels for process collectors

### ISSUE THREAD

**Issue by grantstephens** [prometheus/client_python#268]
Hi

I would like to have labels for process collectors. It looks like it would be possible assuming that all the metrics in a single process collector have the same label.

I do not however know how to change the label on each collection and also don't know if this would actually be useful.

Has anybody come across this use case and have any input?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
