### ISSUE TITLE
Documentation for cleaning metrics path for Flask

### ISSUE THREAD

**Issue by janavenkat** [prometheus/client_python#332]
How often metrics will be cleaned for example if we running the flask framework in docker. I already implemented metrics in the path /metrics.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
