### ISSUE TITLE
Gauges + start_http_server Windows 10, Python 3.6 never updates value after initial set

### ISSUE THREAD

**Issue by kevroy314** [prometheus/client_python#360]
I'm trying to call .set on some Gauge objects every so often, and I've noticed all the values are correct when start_http_server initially runs, but they never update past that. Am I missing something or is this a bug? Here's the relevant code...
```
def process_request(gauges, plugs):
    plug_levels = get_plug_levels(plugs)
    for gauge, level in zip(gauges, plug_levels):
        gauge.set(level)
gauge_ids = [...]
gauge_names = [...]
PLUG_GAUGES = [Gauge(gauge_id, gauge_name) for gauge_id, gauge_name in zip(gauge_ids, gauge_names)]

port = 9001
logging.info('Starting HTTP server on port {0}.'.format(port))
# Start up the server to expose the metrics.
start_http_server(port)

update_interval = 5000
logging.info('Executing data pull at intervals of {0}ms.'.format(update_interval))
# Generate some requests.
while True:
    process_request(PLUG_GAUGES, all_plugs)
    time.sleep(update_interval)
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
