### ISSUE TITLE
Is it possible to have a sample for a flask app using prometheus client to expose one metric ?

### ISSUE THREAD

**Issue by Geoffrey42** [prometheus/client_python#376]
Hi,

I want to build an exporter to expose some metrics from a router to Prometheus using your client.
Since I also want to "trigger" the exporter to execute some ssh command using URL I naturally find Flask as a good choice.

The problem is I juste can't figure out how to use the wsgi dispatcher from your README.
If at least you could add a little more to the existing snippet. Like how to expose one metric to prometheus alongside a flask-like route. Because for now it's really unclear.

If my request is completely off topic, please let me know

Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Geoffrey42** [comment]
Thanks for your reply, I'll do just that
