### ISSUE TITLE
What is the meaning of the argument labelvalues in the init function？

### ISSUE THREAD

**Issue by ilpan** [prometheus/client_python#389]
when a metric is constructed with labelvalues，it won't be registered by a registry, that means in generate_latest won't collect this metric，so I'm confused with the argument labelvalues.

![image](https://user-images.githubusercontent.com/23193162/55272300-6b2bab80-52f5-11e9-98a9-ea96f4ba0020.png)

![image](https://user-images.githubusercontent.com/23193162/55272282-36b7ef80-52f5-11e9-9f55-0839203debd9.png)

![image](https://user-images.githubusercontent.com/23193162/55272289-49cabf80-52f5-11e9-982e-5c7851098e14.png)

**Comment by brian-brazil** [comment]
That's an internal class, not something you should be using directly.

It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
