### ISSUE TITLE
Error cannot import name _floatToGoString

### ISSUE THREAD

**Issue by sandr30** [prometheus/client_python#391]
from prometheus_client.core import GaugeMetricFamily, _floatToGoString
ImportError: cannot import name _floatToGoString
No start service. Help me!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by IrSent** [comment]
Whoever might need it: `_floatToGoString` helper function in newer releases is located in `utils` and called `floatToGoString`:
```
from prometheus_client.utils import floatToGoString
```
