### ISSUE TITLE
push_to_gateway resets gauges if declared globally

### ISSUE THREAD

**Issue by Ashish-Bansal** [prometheus/client_python#404]
Hello everyone!

I found that if I declare
```
gauge_foo = Gauge(
    'foo',
    'Gauge Foo',
    registry=prometheus_registry,
)
```

and then call `push_to_gateway`, it will send `0` value for the gauge to the push gateway. I gave a quick look in the code https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L71. I personally feel this is incorrect behaviour, atleast for gauge. It shouldn't send the `0` value unless `gauge.some_operation` isn't called on the object. If there's any reasoning behind this design decision, I'm looking forward to it. 

Thanks!

**Comment by brian-brazil** [comment]
You asked to push the gauge, so it pushed the gauge. Metrics have a default value of 0.

**Comment by Ashish-Bansal** [comment]
In some production application, there will be lot of gauges. Let's say all of them are globally defined and at some point, we have set 1 out of n gauges. We can't call `push_to_gateway` to update that metric in prometheus until the very end since it will reset all other n-1 gauges to 0.

**Comment by Ashish-Bansal** [comment]
Also I think it should be clearly mentioned in the docs about gauge that initial value of the metric will be 0 and calling `inc` and `dec` will **only** affect the local value of the gauge, not the gauge value stored in the prometheus(if it has been designed like this intentionally.  Is the behaviour same across all other prometheus client libraries ? ) unlike what happens in statsd.
https://github.com/statsd/statsd/blob/master/docs/metric_types.md#gauges

```
Adding a sign to the gauge value will change the value, rather than setting it.

gaugor:-10|g
gaugor:+4|g
```

**Comment by brian-brazil** [comment]
This sounds like a misunderstanding of the general principles of Prometheus instrumentation, rather than any issues with the client libraries.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
