### ISSUE TITLE
How to track in progess request processed less then 1s?

### ISSUE THREAD

**Issue by ghosthamlet** [prometheus/client_python#435]
I have two problem with prometheus  guage， first: I think the Guage track_inprogress just can track request taken more then 1s to run，the fast request Guage.inc will always be reduced by Guage.dec quickly，no chance stay in memory for prometheus scrape. 

Second: how to count the current db querys? If after one http request，count is 10，and no new request come in，then db query will be 10 forever，if no new request，db query shoud be 0，as no new request，python can not run guage.set/dec，so can prometheus or this library don't use prev old value and default to 0 if no new update to this metric? I think these two problem didnot exists in statsd/graphite，don't know why prometheus so different?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ghosthamlet** [comment]
Thanks, but i am be forbidden to login and use google. Not familiar with prometheus, so i just don't know whether these two problems is only my problems, or other users have the same. Or maybe prometheus is just not suitable for these usage, i have searched on Bing half day, but no clear results.
