### ISSUE TITLE
Storing custom time series data in prometheus

### ISSUE THREAD

**Issue by danny311296** [prometheus/client_python#436]
I have a process constantly generating time series data like [[1562665673.783, '0'], [1562665674.783, '0'], [1562665675.783, '0'], [1562665676.783, '0'], [1562665677.783, '0'], [1562665678.783, '0'], [1562665679.783, '0'], [1562665680.783, '0'], [1562665681.783, '0'], [1562665682.783, '0'], [1562665683.783, '0']], ...

Considering the basic nature of this task, is there any direct way of doing this without using custom collectors, etc ?

**Comment by brian-brazil** [comment]
No, and this is generally not how Prometheus should be used.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
