### ISSUE TITLE
How to add custom alert massages to 9093 alert manager?

### ISSUE THREAD

**Issue by xx-zhang** [prometheus/client_python#440]
How to add custom alert massages to 9093 alert manager? \

> what i want to do is that i want to add msg to alert massages about some process or port info update, and i'not good at edit the alert rule-file. so i want to know how can i do to add alert msg by client_python

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
