### ISSUE TITLE
Singleton HTTP server

### ISSUE THREAD

**Issue by khssnv** [prometheus/client_python#447]
Hi. I didn't find this implement, but it feels like a handy feature.

We have `start_http_server` [makes](https://github.com/prometheus/client_python/blob/a8f5c80f651ea570577c364203e0edbef67db727/prometheus_client/exposition.py#L193) new HTTP server instance on each call.

I use `client_python` to collect application execution metrics. It fires metrics from decorated functions. It seems like:

```python
from prometheus_client import start_http_server, Gauge

start_http_server(3904)

def profiler(func):
    metric = Gauge(func.__qualname__ + "elapsed", "Time spent for a function call")
    def wrapper(*args, **kwargs):
        metric = Gauge(func.__qualname__ + "elapsed", "Time spent for a function call")
        t1 = time.time()
        ret = func(*args, **kwargs)
        t2 = time.time()
        metric.set(dt)
        return ret
    return wrapper
```

As you can see, it starts new HTTP server for each `import` and fails at second import because it use port the same.

What could be handy is a singletone behavior like
```python
start_http_server(port, addr='', registry=REGISTRY, use_existing=False)
```
where it skip new server creation if there is a server on `port` and `use_existing` flag is set.

**Comment by brian-brazil** [comment]
You should only create the server once, usually around your main function.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
