### ISSUE TITLE
How to transfer the CollectorRegistry in multiprocessing

### ISSUE THREAD

**Issue by ben741863140** [prometheus/client_python#451]
I want to transfer a CollectorRegistry which store lots of Gauge from my main process to its fork process with pipe or multiprocessing.queue. However, none of them can do their job. Could u tell me that how can I finish my program ? @brian-brazil

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
