### ISSUE TITLE
Expose timestamp via python client

### ISSUE THREAD

**Issue by salehdeh76** [prometheus/client_python#464]
As you know, there is a place to put timestamp in [prometheus's exposition format.](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details) 

Is there a method in python client, so we'll be able to expose timestamp in prometheus text format?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by spaceone** [comment]
Answer is here: https://github.com/prometheus/client_python/issues/588#issuecomment-1054724554
