### ISSUE TITLE
Question regarding multiprocess with uwsgi

### ISSUE THREAD

**Issue by allenc97** [prometheus/client_python#474]
Hi,

Assuming I have a supervisord controlled nginx + uwsgi combination, with the UWSGI server serving a number of flask app processes. In this case, what is my best option to invoke the multiprocess module's mark_process_dead() if my uwsgi worker process dies and is terminated by master? It seems to me like the only possibility is using python's atexit.

Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
