### ISSUE TITLE
High memory consumption 

### ISSUE THREAD

**Issue by dhananjaysathe** [prometheus/client_python#475]
What is the expected memory overhead of adding this library to code? For 5 metrics in noticed it added ~180mb , that sounds a tad ludicrous.

**Comment by brian-brazil** [comment]
That sounds like you're doing something odd.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by dhananjaysathe** [comment]
Added a query here https://groups.google.com/forum/#!topic/prometheus-users/4tEEJt4YLdA
