### ISSUE TITLE
push_to_gateway failed

### ISSUE THREAD

**Issue by gkany** [prometheus/client_python#476]
``` python
registry = CollectorRegistry()
g_test = Gauge('test-push_data', 'test data', ['label_a', 'b', 'c', 'd'], registry=registry)
while 1:
    if queue is not None:
        data = queue.pop
        print('data: {}'.format(data))  # The output always has data, about 2s apart
        try:
            g_test.labels(data['a'], data['b'], data['c'], data['d'])
            push_to_gateway(prometheus_addr, job='push-data_test_job', registry=registry)
        except Exception as e:
            print(repr(e))  #no exception log
    sleep(0.2)
```

My code format is as above.

There is data on the pushgateway at first, but I can't see the data in a few hours. What's even more strange is that the job is not on the pushgateway. I don't know why.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
