### ISSUE TITLE
Can't import  any functions from prometheus_client with python 3.7.4 

### ISSUE THREAD

**Issue by alextsm** [prometheus/client_python#477]
Hello, Im using latest conda environment with python 3.7.4  and prometheus_client 0.7.1 and cannot import any functions from prometheus_client.
Everything works well with Python 3.6.9

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
