### ISSUE TITLE
Can varying pods in Kube Cluster affect the Metrics results

### ISSUE THREAD

**Issue by PradeepGogulamudi** [prometheus/client_python#486]

**Comment by PradeepGogulamudi** [comment]
Created a custom Metric collection python package which imports functions like Counter from Prometheus_Client. This python package collects the total no. of requests and some other application metrics and route it to /metrics path of that app URL. From this route Prometheus(or Grafana) will in turn those and display. Main goal is to have a layer between my micro-service and Prometheus_client. The issue i have is micro-service is deployed in Kubernetes cluster and pods vary (no. of requests varying every fraction because of pod change). How do i make my MetricsPython package collect correct no. of requests instead of split results because of Varying pods.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
