### ISSUE TITLE
Can I create a counter with no labels? And if not can I set default values some how?

### ISSUE THREAD

**Issue by NadavkOptimalQ** [prometheus/client_python#500]
I started using Prometheus and I when I create a metric (counter for example) and I give empty labels it lets me create it.
When I go and increase I get an error `ValueError: No label names were set when constructing`
If labels are mandatory why does it now fail on creation?
```
    labels = ()
    c = Counter("name", "documentation", labelnames=labels)
    c.labels(labels).inc(3)
```

Also lets say I do define labels, why do I always have to provide all of them? What if some parts of my code don't have all the data? Can I set default values for labels? 

Thank you

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
