### ISSUE TITLE
Provide public interface to examine a metric samples

### ISSUE THREAD

**Issue by ldealmei** [prometheus/client_python#502]
I'm currently developing a helper package to allow developers to easily instrument their code and enforce best practices and internal conventions behind the scenes.

One of my use cases, requires me to be able to have access to the samples set on a metric. However there is no public interface to do so.

`MetricWrapperBase` does implement a `collect()` method which returns the information I am looking for but not in a way that is clean to parse. For example, getting a dictionary of the labels set on a sample.

Would it be possible to provide a public interface to get access to a metric's samples?

Thank you!

**Comment by brian-brazil** [comment]
The collect() method is the interface, and though can go via the registry's collect method instead to be a  bit more general.

**Comment by ldealmei** [comment]
So, you would suggest to parse the repr string of the Metric object?

**Comment by brian-brazil** [comment]
Why would you need to do that? It's a struct.

**Comment by ldealmei** [comment]
So obvisouly I don't get what you're suggesting, if you could be more explicit it would greatly help. Thank you

**Comment by brian-brazil** [comment]
Use the existing APIs, there's an example at https://github.com/prometheus/client_python/blob/master/prometheus_client/bridge/graphite.py

This is a question about existing features, so it makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by ldealmei** [comment]
Thanks
