### ISSUE TITLE
metrics response using flask

### ISSUE THREAD

**Issue by guylissak** [prometheus/client_python#508]
Hi,
I have a microservices app where my worker is implemented in python, I also have flask server running in deamon thread, it has few routes for readiness and liveness (being polled by k8s), in the same flask server which is used as Monitor server i want to make a route which update my prom metrics on each request (the business logic of updating the metrics is cleared and works as expected), what i would like to know is if i can send the metrics in the response on each request, that means i need somehow to get the metrics object, in the node.js client this is done by register.metrics(), so bottom line is it supported in the python client?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
