### ISSUE TITLE
Load metrics from file (or anything else)

### ISSUE THREAD

**Issue by mirceaulinic** [prometheus/client_python#515]
Hello good folks,

This might be a silly question, but I'll here I am: I would need to enable persistence for some metrics (looks like the push gateway might be a no-go for now) and I was thinking to have my app dump the metrics, say into a file (e.g., using the `write_to_textfile` function) - then when the app restarts to firstly attempt to load the metrics from there, so it ensures continuity. I understand this doesn't sound like the most ideal scenario, but such are the constraints am afraid... Anyway, so what I'm asking basically is if there's a way, or anyone is aware, of the counter-part of the `write_to_textfile` function to load the metrics from text into the registry.

Thanks!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mirceaulinic** [comment]
Great, thanks @brian-brazil!
