### ISSUE TITLE
Can't create gauges with labels and sample values

### ISSUE THREAD

**Issue by MoritzFago** [prometheus/client_python#516]
I'd like to have a gauge with labels and a value.
But if i try to do that, I get a AttributeError for _value.
To reproduce:
```python
>>> from prometheus_client import Gauge
>>> g = Gauge('my_inprogress_requests', 'Description of gauge', ['l1','l2'])
>>> g.labels(l1='foo',l2='ba')
<prometheus_client.metrics.Gauge object at 0x1078f5f50>
>>> g.set(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/moritzfago/Softwareprojekt/repo/exporter/lib/python3.7/site-packages/prometheus_client/metrics.py", line 344, in set
    self._value.set(float(value))
AttributeError: 'Gauge' object has no attribute '_value'
```

But:
```
>>> g.labels(l1='foo',l2='ba').set(4)
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by MoritzFago** [comment]
> It makes more sense to ask questions like this on the prometheus-users mailing list rather than in a GitHub issue.
There is no question in my bugreport. Here are questions for you @brian-brazil: Why is my report not a bug report and/or where to direct bugreports?
