### ISSUE TITLE
Misleading behavior due to non-destructive collect()

### ISSUE THREAD

**Issue by FedericoCeratto** [prometheus/client_python#532]
collect() on a gauge does not reset or remove already-collected values.
The same happens when write_to_textfile is called on the registry.
When labels are created dynamically this easily leads to lingering old values being collected forever:

```gauge = Gauge("x","y",labelnames=["l1", "l2"])
gauge.labels("a", "b").set(1)
gauge.collect()
gauge.labels("new_x", "new_y").set(1)
gauge.collect() # Outputs both the old and new gauges
```
The Gauge object does not appear to expose methods to reset all gauges to zero or remove them.

Also, the whole Gauge object cannot be deleted and recreated between each use because it triggers #281

**Comment by brian-brazil** [comment]
This is as expected, it sounds like you are writing an exporter and thus should be using a custom collector.

**Comment by bonnieguo** [comment]
there is a index in prometheus "kube_pod_init_container_status_terminated_reason"
seem it can be reset to null when the index donnt to be observed, how it does

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
