### ISSUE TITLE
Historical exposed metrics memorization

### ISSUE THREAD

**Issue by Dani1994Italy** [prometheus/client_python#534]
Hello,

I found out the follow unexpected beahviour between my prometheus db and customized client_python exporter:

I've tried to delete metrics from prometheus db using follow Web API commands:

- curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]=<name_metric>
- curl -X POST -g "http://localhost:9090/api/v1/admin/tsdb/clean_tombstones

All the time series metric diseppeared from prometheus db but after few seconds, probably after the new scraping iteration, all the time series was restored. (I tried with a two hour time series, very short).
So, the questions is:  was the timeseries SAVED in the client_python exporter (buffer, cache, registry etc) and re-exposed every time to prometheus or the problem is at prometheus db side?

Is it a configurable option?

Thank you,
Daniele.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
