### ISSUE TITLE
set a metric with no data on porpouse

### ISSUE THREAD

**Issue by 1ber** [prometheus/client_python#551]
I have an exporter in which i get some values from an application and i want to show when i can't read the values (instead of keeping the old values). If i try to set the Gauge with None i get an error:

prometheus_client/metrics.py", line 344, in set
    self._value.set(float(value))
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
