### ISSUE TITLE
How to clear old data

### ISSUE THREAD

**Issue by kengan** [prometheus/client_python#555]
I have a  Gauge in my application
I also have a array which saves the metrics
For example 
at 10:00, the array likes this
array[1]="machine{'test'=1}"
array[2]="machine{'test'=2}"
each recod in array is a metrics and using Gauge.labes().set() to update metrics

but at 10:30, the array likes this
array[1]="machine{'test'=1}"
 the second record has been removed

but the Gauge still has the record which has been removed

Can someone help me how to clear the old data? Right now I solve this problem by restarting my application.
Thank  you.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
