### ISSUE TITLE
Windows Metrics for Grafana Dashboard

### ISSUE THREAD

**Issue by Zayan1221** [prometheus/client_python#558]
Hello,
Can I have scripts for these Metrics Windows client.
§ CPU utilization
§ File System utilization
§ System messages (ex. Errors in /var/log/messages) Any critical errors reported in logs
§ Disk INODE utilization
§ System process monitoring (ex. Set of services on a server if they are running or not) Alarm if services are not running.

For Memory I got this executed fine :
100 * (windows_os_physical_memory_free_bytes{instance="$instance"}) / windows_cs_physical_memory_bytes{instance="$instance"}

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
