### ISSUE TITLE
Bug(?): Prometheus multiprocess not working

### ISSUE THREAD

**Issue by trallnag** [prometheus/client_python#565]
I cannot get the Prometheus client to work in multiprocess mode. I managed to reduce my code to the following few lines and the issue still persists. Am I missing something?

https://repl.it/repls/StimulatingDearestSampler

1. Requirements / Dependencies:

* prometheus client 0.8.0

2. Script:

```python
import tempfile
import os

from prometheus_client import Counter, REGISTRY

from prometheus_client import generate_latest, CollectorRegistry
from prometheus_client import multiprocess

COUNTER = Counter("gimp", "green is my pepper")

with tempfile.TemporaryDirectory() as tmpdir:
    print('created temporary directory', tmpdir)
    os.environ["prometheus_multiproc_dir"] = tmpdir

    COUNTER.inc()
    COUNTER.inc()
    COUNTER.inc()
    COUNTER.inc()

    if "prometheus_multiproc_dir" in os.environ:
      registry = CollectorRegistry()
      multiprocess.MultiProcessCollector(registry)
    else:
        registry = REGISTRY

    print(generate_latest(registry))
```

When I run the script I get the following output:

```
created temporary directory /tmp/tmpy_rdbzg4
b''
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
