### ISSUE TITLE
Multiprocess: Only gauge files deleted on child exit?

### ISSUE THREAD

**Issue by carletes** [prometheus/client_python#566]
I noticed that `prometheus_client.multiprocess.mark_process_dead(pid)` only deletes files backing gauge objects for the given `pid`. All other files backing counters, histograms, etc for the same `pid` are kept.

Shouldn't those other files be deleted as well? After reading https://github.com/prometheus/client_python#multiprocess-mode-gunicorn:

> This directory must be wiped between Gunicorn runs (before startup is recommended)

I would have expected them to be deleted, too, because they refer to a process that no longer exists, and keeping them around would produce misleading metrics and waste disk space.

**Comment by brian-brazil** [comment]
This is correct, deleting the counter-ish metrics would cause counters to incorrectly go backwards. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
