### ISSUE TITLE
Prometheus metrics not getting exposed for tasks running from celery workers

### ISSUE THREAD

**Issue by utkarshyadavin** [prometheus/client_python#569]
I am running a Fastapi python server along with multiple celery workers to process tasks in background. So basically two apps are running in parallel. But the prometheus metrics of tasks run by worker process are not getting exposed at the /metrics endpoint. Anybody has any idea how to get around this?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
