### ISSUE TITLE
What is the correct way to terminate the sample program?

### ISSUE THREAD

**Issue by KansaiUser** [prometheus/client_python#570]
In your readme page you have this program 

```
from prometheus_client import start_http_server, Summary
import random
import time

# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')

# Decorate function with metric.
@REQUEST_TIME.time()
def process_request(t):
    """A dummy function that takes some time."""
    time.sleep(t)

if __name__ == '__main__':
    # Start up the server to expose the metrics.
    start_http_server(8000)
    # Generate some requests.
    while True:
        process_request(random.random())

```

When I run it (with spyder) for the first time I got no problem. 
But later I do Ctrl-C to stop the program. 

Then when I try to run it again I got 

> ValueError: Duplicated timeseries in CollectorRegistry: {'request_processing_seconds_created', 'request_processing_seconds_sum', 'request_processing_seconds_count', 'request_processing_seconds'}

This is due to line 31 in your registry.py file. 

What is the correct way to terminate the program so that timeseries are not left hanging on?

**Comment by brian-brazil** [comment]
It's only meant to be run once in a given process. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
