### ISSUE TITLE
Calculate average

### ISSUE THREAD

**Issue by sarikh** [prometheus/client_python#581]
I want to calculate an average_something:
definition:
`Gauge average_sth = Gauge("avg", "dont care")`
`Gauge sum_sth = Gauge("sum", "dont care")`
`Gauge  count_sth = Gauge("count", "dont care")`
use:
`average_sth.set(sum_sth/count_sth)`
and it throws an exception.
is there a good way to do it?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
