### ISSUE TITLE
Different labels for the same metric

### ISSUE THREAD

**Issue by sjs205** [prometheus/client_python#584]
Apologies if this is the wrong place for this.

I'm trying to create a metric that monitors NIC status of the various interfaces on a given host. I've read the naming and label rules, and as I understand it, I should have a single Emum metric, such as, "NIC_operstates" and then add a label for each of the different interfaces, "eth0", "eth1"... Does that sound right? I started with crating a metric for each interface, so "eth0_operstate", but I believe this is incorrect based on the nameing a label conventions. 

So my question is. In a single script, how can I create a single metric, that provides multiple network interface status with different labels. Is this possible? If I create a single metric, how can I give each call of state() a different label? Or have I got this completely wong?

Many thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
