### ISSUE TITLE
labelkwargs incorrectly comparing both key and value to self._labelvalues

### ISSUE THREAD

**Issue by chasezimmy** [prometheus/client_python#605]
Hello!

I've run into an issue when I initialize a Histogram w/ labels, then call `.labels()` and pass kwargs into it, I am getting "Incorrect label names" error.

```
# my code
h = Histogram('name', 'doc', labelnames=['env'], buckets=BUCKETS)
h.labels(env=settings.ENVIRONMENT) # error here
```

Looking around the code, it looks like the comparison between `sorted(labelkwargs) != sorted(self._labelnames)` is the cause. [Found here.](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L159)

My suggestion is adding `.keys()`, in order to compare label names only.
```
if sorted(labelkwargs.keys()) != sorted(self._labelnames):
   raise ValueError('Incorrect label names')
```

**Comment by brian-brazil** [comment]
This code is correct as far as I can see and works for me. Using a dict with sorted produces a list of its keys and there are unittests covering this. Your problem is something else.

Also env is usually a target label, and should not be applied to a /metrics like this. That's a matter for service discovery and relabelling on the Prometheus end.

**Comment by chasezimmy** [comment]
I see, didn't know that about sorted! Thank you for the response, I'll close and keep digging on my end.
