### ISSUE TITLE
ProcessCollector can not using in array

### ISSUE THREAD

**Issue by aviman1109** [prometheus/client_python#608]
I used process collector in array, to monitor multiple processes.
```
collectors=[]
for i in range(len(sd_names)):
    collectors.append(ProcessCollector(namespace=sd_names[i],pid=lambda:  os.popen("pidof "+str(sd_names[i])).read()))
```
But that PID in collect function always keep the last service.

I overwrite class ProcessCollector add `self.pid` in __init__
`self.pid = os.path.join(self._proc, str(self._pid()).strip())`

and replace `pid` in collector function.
It worked.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
