### ISSUE TITLE
Using grafana & Prometheus. How to display the total final value of a Counter

### ISSUE THREAD

**Issue by LFED-FP** [prometheus/client_python#632]
Hey y'all, I have some python code that looks like this

I want to track how many of each type of dog is in the park.
```
DOGS.labels(
    SCRIPT_NAME, ENVIRONMENT, type_of_dog).inc()
```

Say the park has these dogs.
Pitbull x 2
German Shepard x 1
Husky x 5

In grafana I can access information with this type of query
```
METRICS: dogs_total{environment="$environment"}
LEGEND: {{type_of_dog}}
```

Is it possible to simply display the total count into grafana? Seems like all the [prometheus functions](https://prometheus.io/docs/prometheus/latest/querying/functions/) deal with changes over time, standard deviations, etcetc. 

Example:
I would like a bubble chart with 3 bubbles, each displaying the name of the dog type & the total. Is this possible?

**Comment by csmarchbanks** [comment]
Hello! It makes more sense to ask questions like this on the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by LFED-FP** [comment]
Got it, thanks for the information!
