### ISSUE TITLE
Collect metric from multiple files

### ISSUE THREAD

**Issue by YuryHrytsuk** [prometheus/client_python#634]
How can I collect the same metric from multiple files? Should I create new instance of metric but with the same name or import it directly? Maybe there is other way?

**Comment by csmarchbanks** [comment]
Hello, a concrete example may help in understanding your question/is this a concern about the library? If it is a question, 
it may make more sense to ask it on the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
