### ISSUE TITLE
no metric captured when adding Summary.time() decoration over a flask decoration

### ISSUE THREAD

**Issue by zjma** [prometheus/client_python#645]
I'm on win10, python 3.8.

I have 3 flask servers.
Server 1:
```
from flask import Flask,request,jsonify
from prometheus_client import start_http_server, Summary

REQUEST_TIME = Summary('Summ2', 'Summ 2')
app = Flask(__name__)

@app.route("/", methods=["GET"])
def about():
    with REQUEST_TIME.time():
        return jsonify({
            'Version': '1.2.3',
        })

start_http_server(9090)
app.run(host='0.0.0.0', debug=False, port=8088, use_reloader=False)
```

Server 2:
```
from flask import Flask,request,jsonify
from prometheus_client import start_http_server, Summary

REQUEST_TIME = Summary('Summ2', 'Summ 2')
app = Flask(__name__)

@app.route("/", methods=["GET"])
@REQUEST_TIME.time()
def about():
    return jsonify({
        'Version': '1.2.3',
    })

start_http_server(9090)
app.run(host='0.0.0.0', debug=False, port=8088, use_reloader=False)
```

Server 3:
```
from flask import Flask,request,jsonify
from prometheus_client import start_http_server, Summary

REQUEST_TIME = Summary('Summ2', 'Summ 2')
app = Flask(__name__)

@REQUEST_TIME.time()
@app.route("/", methods=["GET"])
def about():
    return jsonify({
        'Version': '1.2.3',
    })

start_http_server(9090)
app.run(host='0.0.0.0', debug=False, port=8088, use_reloader=False)
```

I expect to hit `localhost:8088` a few times and see some metric changes at `localhost:9090`. That's the case for server 1 and 2, but not 3. for Server 3, `localhost:8088` can load fine, but no metric seems to be captured.

**Comment by csmarchbanks** [comment]
Hello,

This behavior is because the order of the decorators you use matters, and the `@app.route` decorator needs to be the outermost decorator. This is noted at https://flask.palletsprojects.com/en/1.1.x/patterns/viewdecorators/.

The reason the metric is not incremented in your server 3 example is that the function that is registered via `@app.route` is just the `about()` function as the `@REQUEST_TIME.time()` decorator is evaluated outside of the routing context. In server 2 the `@REQUEST_TIME.time()` decorator is inside the routing context and is properly called for each request. It can certainly be a bit hard to wrap your head around, but keeping the route decorator at the top is what you want.

Since I do not believe this is an issue with the client_library I am going to close this, but let me know if you think there is a bug.
