### ISSUE TITLE
text_string_to_metric_families does not handle _created metrics

### ISSUE THREAD

**Issue by laurivosandi** [prometheus/client_python#668]
Attempting to parse seemingly correct snippet generated by the Python library itself:

```
# HELP whatever Histogram of whatever
# TYPE whatever histogram
whatever_bucket{le="1.0"} 0.0
whatever_bucket{le="2.0"} 0.0
whatever_bucket{le="3.0"} 0.0
whatever_bucket{le="+Inf"} 0.0
whatever_count 0.0
whatever_sum 0.0
# TYPE whatever_created gauge
whatever_created 1.623691804097139e+09
```

results in `ValueError: Clashing name: whatever_created`

Looks like the `text_string_to_metric_families` doesn't accommodate the inclusion of `_created` metrics referenced in bunch of other issues.

**Comment by csmarchbanks** [comment]
Hello, thank you for raising this issue!

In my testing your sample will succeed for:
```
from prometheus_client.parser import text_string_to_metric_families
```
but fail for
```
from prometheus_client.openmetrics.parser import text_string_to_metric_families
```
is this what you see as well?

If so this is because `whatever_created` is part of the metric family for the `whatever` histogram for OpenMetrics, unlike for the Prometheus format. OpenMetrics states that "The name of a MetricFamily MUST NOT result in a potential clash for sample metric names". Therefore, the snippet you shared is invalid OpenMetrics format and correctly fails as the `whatever_created` gauge can clash with the histogram. See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#suffixes for reference.

Hope that makes sense. I am going to close this issue, but I am happy to reopen it if there is a different issue here!
