### ISSUE TITLE
Can't create a counter with the `_total` metric name suffix

### ISSUE THREAD

**Issue by miroswan** [prometheus/client_python#677]
According to [metric naming best practices](https://prometheus.io/docs/practices/naming/):

```
...should have a suffix describing the unit, in plural form. Note that an accumulating count has total as a suffix, in addition to the unit if applicable.
```

However, [this code](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L30-L31) strips any counter metric with `_total` in the name. The comment mentions that it's done to remain compatible with OpenMetrics. 

Could someone please tell me how the OpenMetrics spec would require this? I would like to remove these lines from the code...or at least make it configurable such that I can still have `_total` as the metric name suffix for counters.

**Comment by csmarchbanks** [comment]
You should still see the `_total` suffix being added to counter metrics when they are exposed. The stripping of `_total` from the name is only for the metadata lines so that with OpenMetrics so they will look like:
```
# HELP my_requests HTTP Requests
# TYPE my_requests counter
my_requests_total{endpoint="/",method="get"} 5.0
```
instead of like:
```
# HELP my_requests_total HTTP Requests
# TYPE my_requests_total counter
my_requests_total{endpoint="/",method="get"} 5.0
```

If that is not the behavior you experience could you provide a code snippet where you are unable to add the `_total` suffix?

**Comment by miroswan** [comment]
Ah ha! Upon further inspection this does appear to be the case. Carry on!
