### ISSUE TITLE
Does Prometheus support User Defined Function?

### ISSUE THREAD

**Issue by AbdelouahabKhelifati** [prometheus/client_python#738]
I am currently working on a benchmark of time series database systems for analytical (complex) queries. These queries are algorithms that cannot (easily) be implemented in SQL/native language so they require a third-party programming language such as C, C++, Python, Java, etc.

Does Prometheus support such a feature of a third-party programming language for User Defined Functions?

**Comment by csmarchbanks** [comment]
Hello, Prometheus does not support custom functions currently, but this idea was discussed during the prometheus dev summit on May 27th, 2021. You can find some information in the [notes](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit#heading=h.a9z8x3bt981) under `Extending PromQL`.

I do not know of any work done in this area yet, but if you are interested in contributing I would suggest reaching out on the [prometheus-developers](https://groups.google.com/forum/#!forum/prometheus-developers) mailing list/create a design document.

Since this is not an issue of the python library I am going to close it.
