### ISSUE TITLE
.remove  and .clear not working with multiprocessing mode

### ISSUE THREAD

**Issue by MarcoRizk** [prometheus/client_python#916]
Trying to remove a given set of labels for a metric doesn't work.
The label value is still readable by the collector after it's presumed removal ?
any suggestions ?

**Comment by hatamiarash7** [comment]
I have this problem too

**Comment by csmarchbanks** [comment]
Yep, this is definitely an issue. At a minimum we should document that they do not work in the multiprocessing section of the readme, but ideally we could figure out a way to support remove/clear in multiprocess.

**Comment by yctomwang** [comment]
@csmarchbanks Hi Chris, I also run into this issue. After looking around the code base I think its because of the disconnection between the remove of Normal Metrics and the multiprocess ones. I thinking add a warning message aswell as in the documentation/README would benefit a lot of others. Happy to put together a PR for this. Thanks again for maintiaining such an awesome libaray!

**Comment by csmarchbanks** [comment]
:+1: That would be great, thank you!

**Comment by yctomwang** [comment]
@csmarchbanks Hi Chris, I got the PR in, would be nice if you could review it when you have free time, thanks again.
