### ISSUE TITLE
Feature request: allow disabling "_created" series from code

### ISSUE THREAD

**Issue by positron96** [prometheus/client_python#933]
At the moment, "_created" series can be disabled by setting PROMETHEUS_DISABLE_CREATED_SERIES environment variable. If one wants to set it from python, he needs to do it before importing prometheus_client, because the value is calculated on import. 
Like this:
```
os.environ['PROMETHEUS_DISABLE_CREATED_SERIES'] = 'true'
import prometheus_client
```
That is not very pythonic, style checkers complain on imports not being at top of the file, etc.

Please add an ability to set this option from code, from function call, of just make `_use_created` variable in `metrics.py` public.

**Comment by jiaxinonly** [comment]
Agreed, the ability to disable from code should be added.

**Comment by csmarchbanks** [comment]
I was looking into doing this and see two options:
1. Allow access to the global variable, probably a function like `disable_created_series()` that sets `_use_created` to false.
2. Allow each registry to have `_created` series enabled/disabled.

Do we know of use cases where some collectors would like to have `_created` series and others do not? My thought is that a global setting is probably good enough since your system will either understand `_created` or not.

**Comment by positron96** [comment]
For me it's good enough to have a global option
