### ISSUE TITLE
Wrong python version required in the prometheus_client conda package for new version (0.18)

### ISSUE THREAD

**Issue by olamarre** [prometheus/client_python#977]
I just asked a [question on Stack Overflow](https://stackoverflow.com/q/77467316/18386585) regarding the fact that the latest version of the [`prometheus_client conda package`](https://anaconda.org/conda-forge/prometheus_client) (0.18) was being installed in my python 3.7 environment as a dependency of `jupyterlab`. But as correctly configured in this github repository, python >= 3.8 is required for version 0.18.

I just saw that the requirements for version 0.18 in conda (mistakenly?) specify python >= 3.6 (instead of 3.8):

![prometheus_client_0-18](https://github.com/prometheus/client_python/assets/7255017/18f95269-c3f3-4425-a7fc-ed26805464a4)

Would it be possible to fix this? Thanks a lot!

**Comment by mfansler** [comment]
Please file the issue here on the [Conda Forge feedstock](https://github.com/conda-forge/prometheus_client-feedstock/issues). Someone there needs to 1) update the recipe to constrain this lower bound and 2) adjust the metadata on previous builds that are non-functional with lower Python versions via a repodata patch.

**Comment by olamarre** [comment]
Ok! [Done](https://github.com/conda-forge/prometheus_client-feedstock/issues/37).
